### ISSUE TITLE
"MqttException: Client is not connected" when building client

### ISSUE THREAD

**Issue by arthurdeschamps** [ctron/kapua-gateway-client#5]
When I try to build the client:

`application = client.buildApplication(applicationId).build();`

I get this exception:

```
org.eclipse.paho.client.mqttv3.MqttException: Client is not connected
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:177)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1126)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1089)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1096)
	at org.eclipse.kapua.gateway.client.mqtt.paho.PahoClient.publish(PahoClient.java:249)
	at org.eclipse.kapua.gateway.client.mqtt.paho.PahoClient.publishMqtt(PahoClient.java:244)
	at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.sendBirthCertificate(KuraBirthCertificateModule.java:173)
	at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.applicationAdded(KuraBirthCertificateModule.java:125)
	at org.eclipse.kapua.gateway.client.spi.AbstractClient.lambda$notifyAddApplication$1(AbstractClient.java:93)
	at org.eclipse.kapua.gateway.client.spi.AbstractClient.fireModuleEvent(AbstractClient.java:85)
	at org.eclipse.kapua.gateway.client.spi.AbstractClient.notifyAddApplication(AbstractClient.java:93)
	at org.eclipse.kapua.gateway.client.spi.AbstractClient.internalBuildApplication(AbstractClient.java:148)
	at org.eclipse.kapua.gateway.client.spi.AbstractClient$2.build(AbstractClient.java:134)
	at communications.kapua.KapuaClient.<init>(KapuaClient.java:73)
	at simulation.main.Simulation.main(Simulation.java:55)
```

**Comment by GogicM** [comment]
@arthurdeschamps 
Hi. I just used this library, and woks good. Can you provide your code here (or link to your repo)?

**Comment by arthurdeschamps** [comment]
Hi. Thanks for the assistance.
Here is the code:


        final int port = 1883;
        final String host = "localhost";
        final String accountName = "kapua-sys";
        final String applicationId = "kapua-iot-gateway-simulation-scm";
        final String clientId = "supply-chain-control-simulation";
        try {
            client = KuraMqttProfile.newProfile(PahoClient.Builder::new)
                    .accountName(accountName)
                    .clientId(clientId)
                    .brokerUrl("tcp://"+host+":"+Integer.toString(port))
                    .credentials(userAndPassword(accountName, "kapua-password"))
                    .build();

        } catch (Exception e) {
           logger.error(e.getMessage());
        }

        application = client.buildApplication(applicationId).build();

Actually even though this exception occurs everything still works. It would just be cleaner not to have it.

**Comment by GogicM** [comment]
Hm... I don't know it's error, but account name is `kapua-sys`, but user name is : `kapua-broker` ... Try to send `kapua-broker` to `credentials(userAndPassword(userName, password))` method

**Comment by arthurdeschamps** [comment]
It doesn't solve it :( 
I forgot to mention there is another warning just before the exception occurs:
`11:20:46.131 [main] WARN org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule - Failed to publish birth certificate`

**Comment by GogicM** [comment]
Hmm... It si problem with birth certificate. At first connection, it is supposed to client publish birth message to register device (creates new device entry)...I only used FuseClient instead PahoClient. Can you show me publish code?
Also, try to set kapua IP address instead `localhost`

**Comment by ctron** [comment]
The issue is caused by the fact that the birth certificate is sent out while the client is still disconnected. This will raise an issue when using Paho IIRC. However the birth certificate will also be sent out when the client gets connected. So that is more like an information than a warning in this case.

I am open to suggestions what a good fix could be.

**Comment by noumanjamil16** [comment]
11:20:46.131 [main] WARN org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule - Failed to publish birth certificate 
@GogicM @arthurdeschamps @ctron i am facing same error while running my maven project on eclipse. Please help me.

**Comment by ctron** [comment]
What help do you need? Is there anything not working?

**Comment by noumanjamil16** [comment]
I want this exception to be resolved mentioned in comment above

**Comment by ctron** [comment]
Does it cause any troubles?

**Comment by noumanjamil16** [comment]
And is there any way to use android dependency? I want to use it in android application with cradle dependencies instead of maven

**Comment by noumanjamil16** [comment]
@ctron any guidance on it ?

**Comment by ctron** [comment]
Not really, works the same as all other Java dependencies. Nothing special here.
